apiVersion: v1
kind: Service
metadata:
  name: k8s-job-manager
  labels:
    app: k8s-job-manager
spec:
  type: NodePort
  selector:
    app: k8s-job-manager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
