name: 'Close stale issues and PRs'
# documentation: https://github.com/marketplace/actions/close-stale-issues
on:
  schedule:
    # https://crontab.cronhub.io/
    - cron: '52 4 * * Mon'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: 'Notice of Inactivity: This issue has been open for 8 weeks with no activity. To prevent it from being automatically closed in 2 weeks, please add a comment or remove the "stale" label.'
          days-before-stale: 56
          days-before-close: 14
          exempt-all-pr-assignees: true
